---
- name: amit akarsz
  hosts: localhost
  connection: local

  tasks:
    - name: Set facts for URI
      set_fact:
        tower_host: '{{ lookup("env", "TOWER_HOST") }}'
        tower_username: '{{ lookup("env", "TOWER_USERNAME") }}'
        tower_password: '{{ lookup("env", "TOWER_PASSWORD") }}'

    - name: First call to get template data
      uri:
        url: "{{ tower_host }}/api/v2/job_templates/"
        return_content: true
        user: "{{ tower_username }}"
        password: "{{ tower_password }}"
        force_basic_auth: true
        validate_certs: false
        method: GET
      register: templates

    - name: facts are setting 
      set_fact:
        templates_pagesize: "{{ templates['json']['count'] }}"
        